#!/bin/bash

# Change to out-of-source build directory.
cd ./build

# Clean build directory.
cmake --build . --target clean

# Invoke CMake.
cmake -DCMAKE_BUILD_TYPE=Debug ..

# Make the required example.
cmake --build .
