#pragma once

#include "../src/registers/clocks.hpp"
#include "../src/registers/io.hpp"
#include "../src/registers/nvic.hpp"
#include "../src/registers/pads.hpp"
#include "../src/registers/pll.hpp"
#include "../src/registers/resets.hpp"
#include "../src/registers/rtc.hpp"
#include "../src/registers/sio.hpp"
#include "../src/registers/ssi.hpp"
#include "../src/registers/timer.hpp"
#include "../src/registers/uart.hpp"
#include "../src/registers/watchdog.hpp"
#include "../src/registers/xip.hpp"
#include "../src/registers/xosc.hpp"
